[nexus]
; Get your API key from: https://www.nexusmods.com/users/myaccount?tab=api
; Copy this file to config.ini and paste your key below
; NEVER commit config.ini to GitHub
api_key = QaniZmGL/RkDPFnGxgCuF4d0DcORlP9wzQ8nz/nByYo9JcZfww==--doS/rJAB47EKLJo5--Li8BoNv9vi3N46w7yvrdgw==
